data_dir: /home/hinge_local/bic-mac-data/train

batch_size: 2
num_workers: 0

epochs: 250
learning_rate: 0.0003

patch_size: [192,192,192]

input_modalities:
  - nacpet
  # - topogram
  # - mri_combined_in_phase
  # - mri_combined_out_phase