data_dir: /depict/users/hinge/shared/bic-mac-data/hf_dataset/train

batch_size: 2
num_workers: 4

epochs: 100
learning_rate: 0.0001

patch_size: [128,128,128]

spacing: [1.5234375,1.5234375,2.0]

input_modalities:
  - nacpet
  - topogram
  - mri_combined_in_phase
  - mri_combined_out_phase